CREATE DATABASE COMPANY
USE COMPANY
CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(20) NOT NULL
)
INSERT INTO VEZIFE VALUES('Satici')
INSERT INTO VEZIFE VALUES('Kassir')
INSERT INTO VEZIFE VALUES('Manager')


CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
SURNAME NVARCHAR(30) DEFAULT('XXXX'),
NAME NVARCHAR(20) NOT NULL,
FNAME NVARCHAR(20) NOT NULL,
VezifeID INT REFERENCES VEZIFE(ID),
SALARY FLOAT
)
INSERT INTO ISCI(SURNAME,NAME,FNAME,SALARY) VALUES('VAHABOVA','ELNARA','ELCIN',3,5000)
INSERT INTO ISCI(SURNAME,NAME,FNAME,SALARY) VALUES('VAHABOV','ELNAR','ELCIN',1,450)
INSERT INTO ISCI(SURNAME,NAME,FNAME,SALARY) VALUES('VAHABOVA','FATIMA','ELCIN',2,3700)


CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(20) NOT NULL
)
INSERT INTO FILIAL VALUES('T-SHIRT')
INSERT INTO FILIAL VALUES('JEANS')
INSERT INTO FILIAL VALUES('DRESS')

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(20) NOT NULL,
aPRICE FLOAT,
sPRICE FLOAT
)
INSERT INTO MEHSUL VALUES('A',2,4)
INSERT INTO MEHSUL VALUES('B',3,14)
INSERT INTO MEHSUL VALUES('C',5,10)

CREATE TABLE SATIS(
ID INT PRIMARY KEY IDENTITY,
MehsulID INT REFERENCES MEHSUL(ID),
IsciID INT REFERENCES ISCI(ID),
FilialID INT REFERENCES FILIAL(ID),
SoldDATE DATE DEFAULT GETDATE()
)
INSERT INTO SATIS VALUES(1,3,1,'2022-04-12')
INSERT INTO SATIS VALUES(2,2,3,'2022-04-20')
INSERT INTO SATIS VALUES(3,1,2,'2022-04-17')

SELECT I.SURNAME,I.NAME,I.FNAME,F.NAME 'Filial adi',M.NAME 'Mehsul adi',M.aPRICE 'Alis qiymeti',M.sPRICE 'Satis qiymeti'
FROM SATIS AS S 
JOIN ISCI AS I
ON S.IsciID=I.ID

JOIN FILIAL F
ON S.FilialID=F.ID

JOIN MEHSUL M
ON M.ID=S.MehsulID

SELECT SUM(sPRICE) FROM SATIS AS S
JOIN MEHSUL AS M
ON M.ID=S.MEHSULID

SELECT SUM(sPRICE) FROM SATIS AS S
JOIN MEHSUL AS M
ON M.ID=S.MEHSULID
WHERE MONTH(S.SoldDATE)=MONTH(GETDATE())

SELECT COUNT(*) 'Iscinin satdigi mehsul sayi' FROM SATIS GROUP BY ISCIID

SELECT TOP 1 MEHSUL.NAME , COUNT(MEHSULID) AS 'MAX SOLD PRODUCTS' FROM SATIS
INNER JOIN MEHSUL ON SATIS.MEHSULID = MEHSUL.ID
WHERE MONTH(SATIS.SoldDATE) = MONTH(GETDATE())
GROUP BY MEHSUL.NAME
ORDER BY COUNT(MEHSULID) DESC
